### ISSUE TITLE
Killing LizardMen shows armor stands

### ISSUE THREAD

**Issue by joejoethemonkeys** [DestinyNetwork/DungeonRealms-Bug-Report#120]
When I kill a lizardman, t2, right outside of Tripoli, right before they die, I see an armorstand popup, then a second later it disappears, its a visual glitch, not something that affects gameplay to majorly though.

**Comment by Proxying** [comment]
@Xwaffle1

**Comment by joejoethemonkeys** [comment]
Update on this matter: It comes from the Dmg indicators that float around, not the actual lizardman

**Comment by joejoethemonkeys** [comment]
This is also most likely cause the problem with the hitting, its detecting the player is hitting the armor stands instead of the mob, which gives affect the player hit the mob, but in actuality the player just hit the floating armor stand...
