### ISSUE TITLE
Cannot create orb with t3 scrap

### ISSUE THREAD

**Issue by FatChicks** [DestinyNetwork/DungeonRealms-Bug-Report#141]
The title says it all it used to take 64+56 to create a orb and its not letting anyone. please fix this.

**Comment by Brucosify** [comment]
The DR code was updated in the last release to NOT allow iron scrap to be made into orbs. Only T4 & T5 scraps can make orbs. I'll let the powers that be decide if they want keep this decision or reverse it. Personally, it made orbs rarer (and more expensive) and T3 enchants more common which helps most mid-tier players.

**Comment by FatChicks** [comment]
It also removes any reason to honostly mine because I don't mine for enchants I mine for orbs and past t2 mining is a even bigger pain.

**Comment by Brucosify** [comment]
T2 mining is still too slow. I used to be able to do the whole right wall of Gloomy Cave before it re-generated. I think that I can do maybe 1/2 now. I'll confirm later.
