### ISSUE TITLE
Lost Everything

### ISSUE THREAD

**Issue by joejoethemonkeys** [DestinyNetwork/DungeonRealms-Bug-Report#145]
Well this is a bug where... The server crashes.... i log in..... i have nothing.... and now i have nothing, i'm guessing it has to do with saving the player data and the player data doesnt get loaded in right, and I log in, then it overwrites the old player data.

**Comment by NeturonicAngelz** [comment]
To Sync your data use the following command:
- /logout

I personally try logging out every hour while playing, or before a restart, or whenever lag starts occurring really badly. Nevertheless if you are looking for compensation for the lose of your items, they recently posted this on the news information section:

- http://dungeonrealms.net/home/m/21114663/article/3495390

And it states that it is alpha there will be wipes.
