### ISSUE TITLE
Mining Speed Bug (With Possible Fix)

### ISSUE THREAD

**Issue by MultR** [DestinyNetwork/DungeonRealms-Bug-Report#146]
This is something I have heard most players talk about. At the current moment, mining has become so slow, it is pretty much undoable. I am not to sure of what the problem is, but I do happen to know that Mining Fatigue plays a large role. What I would like to suggest is to let the community test mining without Mining Fatigue, or if that seems too fast, setting Picks to give varying levels of haste upon contact with a block. Ex: Haste 2, Mining Fatigue 2 when mining a T2 Ore with a T2 Pick. Haste 4, Mining Fatigue 3 when mining a T1 Ore with a T1 Pick. ect. This could be a possible work around (FOR THE TIME BEING) until there becomes a way to deal with the current problems affecting Mining Fatigue.

**Comment by Proxying** [comment]
Mining speed has already been lowered and won't be altered again.

**Comment by FatChicks** [comment]
wtf that ruins the point in mining which is honostly stupid af because it used to be Mining Fatigue 1

**Comment by Proxying** [comment]
That's a shame
