### ISSUE TITLE
Inventory gets reset every login

### ISSUE THREAD

**Issue by joejoethemonkeys** [DestinyNetwork/DungeonRealms-Bug-Report#154]
I made a post about this before, but now I have more info. Everytime I log in, for the past few days, my inventory gets wiped, except for the nether crystal and the hearthstone, and also 1 Character Journal, but everytime i log in, ANOTHER hearthstone/nether star spawns in my inventory...

![](http://i.imgur.com/GFSVueh.png)

**Comment by NeturonicAngelz** [comment]
You can fix the getting additional Realm Portals / Hearth Stones by doing the following:

- Put all of your valuable materials inside of your Bank. Then type the following command:
/suicide , ensure you accept the suicide request and you will receive a normal number of
realm portals and Hearthstones.
