### ISSUE TITLE
Spawning chunk not loading (on 1st login)

### ISSUE THREAD

**Issue by molter00** [DestinyNetwork/DungeonRealms-Bug-Report#167]
When you first login, the initial chunk does not load:
![2015-09-12_15 38 08](https://cloud.githubusercontent.com/assets/14539795/9986142/f6789d46-6038-11e5-84e7-8c02fdfb5bf7.png)
Then, after a few relogs, it ends up working, but you have things on the inventory you shouldn't:
![2015-09-12_15 38 48](https://cloud.githubusercontent.com/assets/14539795/9986148/0c70349c-6039-11e5-8134-da5fb55eda35.png)

**Comment by NeturonicAngelz** [comment]
This seems more like a clientside visual chunk / material glitch. Somethings like this can occur due to lag and various other issues that are happening on the server, I'm sure if you were to attempt to place those items frames or move them around they will disappear.

**Comment by PhdNick** [comment]
We're aware of the issue and have implemented future code to stop this.
