### ISSUE TITLE
Unable to join US-3

### ISSUE THREAD

**Issue by Silvre** [DestinyNetwork/DungeonRealms-Bug-Report#179]
After US-3 rebooted to apply a patch, I am now unable to join US-3, because I'm still apparently logged in.  Should I note that I'm still unable to log in several hours after it first started occurring, which at this point is becoming very irritating and very absurd.

**Comment by PhdNick** [comment]
Should be fixed now.

**Comment by Silvre** [comment]
Still says my account(Silvre) is still logged on, and attempting to be synced.
