### ISSUE TITLE
Parties Cause Lag

### ISSUE THREAD

**Issue by LifeIsntFair** [DestinyNetwork/DungeonRealms-Bug-Report#27]
Whenever Two or more people are in a party it makes the server lag a little, the more parties the more Laggy it gets

**Comment by Proxying** [comment]
We had 5 people in a party earlier and everyone said there was no lag? Will look into it.

**Comment by GetShot** [comment]
Yeah it was working earlier then it started to lag again a bit later whenever you would join someones party
