### ISSUE TITLE
Body "Duplication"

### ISSUE THREAD

**Issue by Deathypus** [DestinyNetwork/DungeonRealms-Bug-Report#49]
Last night I logged out without doing /logout and I wasn't able to come back on. Today I was able to and when walking paste where I was, I found myself. 

![](http://i.imgur.com/LHGVZ7D.png)
Wasn't able to kill him or anything, but I'm able to hit him and it makes a hit noise and treats it as if he was hit.

**Comment by PhdNick** [comment]
Combat log issue, is being actively worked on!
