### ISSUE TITLE
Pickaxe Speed (T1)

### ISSUE THREAD

**Issue by DatKashi** [DestinyNetwork/DungeonRealms-Bug-Report#62]
When mining T1 (coal) ore with a T3 (wood) pickaxe, it does so at vanilla (or maybe even slower?) speed. You still get the rewards, but it takes an absurd about of time to mine the ore

**Comment by 660bryan** [comment]
wood pickaxe is tier 1... but I aggree that it takes WAY LONGER to mine now then in the old dungeon Realms... mining fatigue 3?!...wasnt it supposed to be 2 or 1?
