### ISSUE TITLE
Negative Stat Points

### ISSUE THREAD

**Issue by Deathypus** [DestinyNetwork/DungeonRealms-Bug-Report#66]
I don't remember how this happened, but somehow when I logged on I had negative Stat points... 

![](http://i.imgur.com/avm18Rc.png)

**Comment by Deathypus** [comment]
note: I was back with 6 points next level.

**Comment by Deathypus** [comment]
and then they disappeared again... Something fishy with Stat Points

**Comment by Deaner144** [comment]
Yeah i got the same problem

**Comment by Xwaffle1** [comment]
Fixed! :)
