### ISSUE TITLE
Negative Skills Points to Allocate

### ISSUE THREAD

**Issue by Deaner144** [DestinyNetwork/DungeonRealms-Bug-Report#75]
After i had leveled to level 12 i had 12 points to allocate and i allocated them then just after leveling to 13 i have -6 points to allocate.
![image](https://cloud.githubusercontent.com/assets/14261672/9837422/f03df8bc-5a35-11e5-8065-13705e3d01be.png)
This is an issue i have found and am not sure if others have experienced this or not.

**Comment by Xwaffle1** [comment]
Fixed!
