### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by ImpaTheImpaler** [DestinyNetwork/DungeonRealms-Bug-Report#79]
When you try to mine coal it takes about 20 seconds to mine one coal ore, this needs to be rebalanced as it makes mining take even longer than it did.

**Comment by Xwaffle1** [comment]
Fixed :)

**Comment by Deaner144** [comment]
Mining coal takes around  1 Minute and 20 seconds to mine 1 coal ore with a T1 level 1 Pick
