### ISSUE TITLE
Leveling imbalances/T1 scaling xp

### ISSUE THREAD

**Issue by simplenmm** [DestinyNetwork/DungeonRealms-Bug-Report#80]
Currently the only way to gain levels effectively(or at all) is farming t1(levels 15-20). Every time you level up the tier ones give you more experience instead of a flat rate. This may not be a bug but it is a serious coding flaw that will restrict as well as inhibit players from enjoying themselves. I would be happy to punch numbers and find a solid flat rate of experience for each tier that would allow players to level effectively by farming the tier that they are supposed to be at that time. The reason i feel a need to call attention to this is because I found myself farming t4 the moment I had reached level 20. Playing this far ahead and not being rewarded by it becomes frustrating and tedious because any drops i get i cannot use until I reach level 30, which is only possible if I want to farm tier 1 for 4 hours in a t3 set. This may not be a "bug" but it is a serious issue that needs to be addressed and affects the overall state of the game. Feel free to ask me for help to find flat rates for the experience of mobs.

**Comment by Proxying** [comment]
Testing out a new exp system based on the results of the poll http://strawpoll.me/5487353/r.
